### ISSUE TITLE
Running platypush on Pi 3

### ISSUE THREAD

**Issue by WojtekKozaczynski** [BlackLight/platypush#134]
Now, after resolving installation issues (see isue #133), I am running into problems starting the platypush service. I am following your post "How to Transform a RaspberryPi Into a Universal Zigbee and Z-Wave Bridge". I created ~/etc/platypush/config.yaml file with this content
```
backend.http:
    port: 8008
zwave:
    device: /dev/ttyACM0
backend.zwave:
    enabled: true
```
_The /dev/ttyACM0 is what showed up after I plugged the Z-Wave USB transceiver into the Pi._

The first launch failed with an error indicating that bcypt module was missing. Since python2 is Raspbian's default I had to use the following to load the module 
```
sudo python3 -m pip install bcrypt
```
Below is the SSH console output of the second launch 
``` 
pi@piTwo:~/platypush $ platypush
2020-05-14 22:36:52,283| INFO|platypush|---- Starting platypush v.0.12.6
2020-05-14 22:36:53,370|WARNING|platypush|Traceback (most recent call last):
2020-05-14 22:36:53,371|WARNING|platypush|  File "/usr/local/bin/platypush", line 11, in <module>
2020-05-14 22:36:53,371|WARNING|platypush|load_entry_point('platypush==0.12.6', 'console_scripts', 'platypush')()
2020-05-14 22:36:53,372|WARNING|platypush|  File "/usr/local/lib/python3.7/dist-packages/platypush-0.12.6-py3.7.egg/platypush/__init__.py", line 199, in main
2020-05-14 22:36:53,373|WARNING|platypush|app.start()
2020-05-14 22:36:53,373|WARNING|platypush|  File "/usr/local/lib/python3.7/dist-packages/platypush-0.12.6-py3.7.egg/platypush/__init__.py", line 171, in start
2020-05-14 22:36:53,374|WARNING|platypush|self.backends = register_backends(bus=self.bus, global_scope=True)
2020-05-14 22:36:53,374|WARNING|platypush|  File "/usr/local/lib/python3.7/dist-packages/platypush-0.12.6-py3.7.egg/platypush/context/__init__.py", line 53, in register_backends
2020-05-14 22:36:53,375|WARNING|platypush|b = getattr(module, cls_name)(bus=bus, **cfg, **kwargs)
2020-05-14 22:36:53,376|WARNING|platypush|TypeError
2020-05-14 22:36:53,376|WARNING|platypush|:
2020-05-14 22:36:53,376|WARNING|platypush|__init__() missing 1 required positional argument: 'device'
```
It looks like this time it is looking for 'device" argument, which I assumed should have come from the config file(?)

**Comment by BlackLight** [comment]
Specify the device option on the backend instead of the plugin:

```
backend.zwave:
    device: /dev/ttyACM0

zwave:
    enabled: True
```

**Comment by WojtekKozaczynski** [comment]
I made the above modifications to the config file, but the service failed with error ```WARNING|platypush|No module named 'python_openzwave```. That module is not in the ```requirements.txt``` file, so I had to install it separately. 
After that the service started, although it generated a bunch of __INFO|ZwaveBackend|Received unhandled ZWave event__ messages with a large JSON object attached. 
Once I logged into the service from a browser on my laptop and got through the login page the console first started showing error messages related to SQLAlchemy like this one __ProgrammingError: SQLite objects created in a thread can only be used in that same thread__. Then it stabilized and I tried to add a GE Z-Wave smart electric wall plug, but the service seems to be stuck in some kind of loop that generates the following sequence of messages
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/platypush-0.12.6-py3.7.egg/platypush/backend/__init__.py", line 236, in run
    self.loop()
  File "/usr/local/lib/python3.7/dist-packages/platypush-0.12.6-py3.7.egg/platypush/backend/zwave/__init__.py", line 259, in loop
    self._process_event(event)
  File "/usr/local/lib/python3.7/dist-packages/platypush-0.12.6-py3.7.egg/platypush/backend/zwave/__init__.py", line 151, in _process_event
    network = event.network or self.network
AttributeError: 'ZwaveNetworkStoppedEvent' object has no attribute 'network'
2020-05-16 23:36:16,455| INFO|openzwave|Stop Openzwave network.
2020-05-16 23:36:16,455| INFO|openzwave|Stop Openzwave network.
2020-05-16 23:36:16,459| INFO|openzwave|ZWave configuration written to user directory.
2020-05-16 23:36:16,459| INFO|openzwave|ZWave configuration written to user directory.
2020-05-16 23:36:21,482| INFO|openzwave|Start Openzwave network.
2020-05-16 23:36:21,482| INFO|openzwave|Start Openzwave network.
2020-05-16 23:36:21,666| INFO|openzwave|Driver ready using library Static Controller version Z-Wave 4.61
2020-05-16 23:36:21,666| INFO|openzwave|Driver ready using library Static Controller version Z-Wave 4.61
2020-05-16 23:36:21,667| INFO|openzwave|home_id 0xc45f3127, controller node id is 1
2020-05-16 23:36:21,667| INFO|openzwave|home_id 0xc45f3127, controller node id is 1
2020-05-16 23:36:21,669| INFO|openzwave|Driver ready using library Static Controller version Z-Wave 4.61
2020-05-16 23:36:21,669| INFO|openzwave|Driver ready using library Static Controller version Z-Wave 4.61
2020-05-16 23:36:21,670| INFO|openzwave|home_id 0xc45f3127, controller node id is 1
2020-05-16 23:36:21,670| INFO|openzwave|home_id 0xc45f3127, controller node id is 1
2020-05-16 23:36:21,672| INFO|openzwave|Driver ready using library Static Controller version Z-Wave 4.61
2020-05-16 23:36:21,672| INFO|openzwave|Driver ready using library Static Controller version Z-Wave 4.61
2020-05-16 23:36:21,673| INFO|openzwave|home_id 0xc45f3127, controller node id is 1
2020-05-16 23:36:21,673| INFO|openzwave|home_id 0xc45f3127, controller node id is 1
2020-05-16 23:36:21,675| INFO|openzwave|Driver ready using library Static Controller version Z-Wave 4.61
2020-05-16 23:36:21,675| INFO|openzwave|Driver ready using library Static Controller version Z-Wave 4.61
2020-05-16 23:36:21,676| INFO|openzwave|home_id 0xc45f3127, controller node id is 1
2020-05-16 23:36:21,676| INFO|openzwave|home_id 0xc45f3127, controller node id is 1
```

Needless to say, I have no clue where to take it from here (?)

**Comment by BlackLight** [comment]
- The `python-openzwave` dependency is actually [reported in the `requirements.txt`](https://github.com/BlackLight/platypush/blob/master/requirements.txt#L231), as well the [plugin documentation](https://platypush.readthedocs.io/en/latest/platypush/plugins/zwave.html) and the [`setup.py`](https://github.com/BlackLight/platypush/blob/master/setup.py#L285), and the dependency can be easily installed through this command (same procedure described in the [original Medium article](https://medium.com/the-monolith/transform-a-raspberrypi-into-a-universal-zigbee-and-z-wave-bridge-b686cdd1849e)):

```
pip install 'platypush[zwave]'
```

- It seems that the network object isn't correctly initialized in your case. For sake of robustness [I've just submitted a patch for it](https://github.com/BlackLight/platypush/commit/51f99026ac7e8523887612bee4563d1e1b855076), you can install the new release or pull the latest changes and see if the error on `ZWaveNetworkStoppedEvent` still occurs. However, it seems to me that the system is struggling at connecting to your Z-Wave adapter. You shouldn't normally have a `ZWaveNetworkStoppedEvent` unless the network was explicitly stopped. It'd be helpful to see what happens in your logs before the `ZWaveNetworkStoppedEvent`, as I suspect some communication issue with the adapter.

- The `INFO|ZwaveBackend|Received unhandled ZWave event` log events aren't anything suspicious - it's simply that the backend doesn't have (and probably doesn't need) a logic to react to all the possible events generated by the Z-Wave stack. If you believe however that the app is missing some event required by your application please post the content of the event.

- The `ProgrammingError: SQLite objects created in a thread can only be used in that same thread` error is annoying but harmless. Platypush is a heavily multithreaded application, while the SQLite Python driver is not thread-safe. I have made it thread-safe as much as possible by locking any transaction on the database, but I don't have control on the rollback logic - when objects are deallocated. Those errors come from the rollback context. I know they are noisy, but they have no functional impact, and I don't have much control to suppress them either because they are triggered by the SQLite stack.

**Comment by WojtekKozaczynski** [comment]
On a clean installation I still see one issue. If I put the ```config.yaml``` file in the ```/home/pi/.config/platypush``` directory I get the following on startup (I am running as ```pi``` su)
```  
Traceback (most recent call last):
  File "/usr/local/bin/platypush", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/platypush/__init__.py", line 198, in main
    app = Daemon.build_from_cmdline(sys.argv[1:])
  File "/usr/local/lib/python3.7/dist-packages/platypush/__init__.py", line 113, in build_from_cmdline
    no_capture_stderr=opts.no_capture_stderr)
  File "/usr/local/lib/python3.7/dist-packages/platypush/__init__.py", line 76, in __init__
    Config.init(self.config_file)
  File "/usr/local/lib/python3.7/dist-packages/platypush/config/__init__.py", line 344, in init
    _default_config_instance = Config(cfgfile)
  File "/usr/local/lib/python3.7/dist-packages/platypush/config/__init__.py", line 65, in __init__
    .format(self._cfgfile_locations))
RuntimeError: No config file specified and nothing found in ['/root/.config/platypush/config.yaml', '/etc/platypush/config.yaml']
```
So it seems that the app is not looking for```~/.config/platypush``` but for ```/root/.config/platypush/``` directory. After moving the config file to the ```/etc/platypush/``` tha app starts fine. 

I am still running into problems with Z-Wave backend, but I will open a separate issue for that.

**Comment by BlackLight** [comment]
If you use su to launch the application then the effective user_id changes to root, and the configuration file will be searched in /root. Running platypush as root is usually not a very wise idea anyway - keep in mind that all the commands you execute on the device will be executed as root.
