### ISSUE TITLE
Add an alarm in an event hook

### ISSUE THREAD

**Issue by Duncankn** [BlackLight/platypush#137]
Hi there,

I have an event hook which is listening to a motion sensor, the light will turn on when 'occupancy' is 1 and an alarm will be created.
The alarm will turn off the light after 2 minutes, but unfortunately, the alarm was failed to be created. Is there anything wrong what I have setup?
Thank!

There is the event hook in config.yaml.

```yaml
event.hook.PirTriggerLightOn:
    if:
        type: platypush.message.event.zigbee.mqtt.ZigbeeMqttDevicePropertySetEvent
        device: 'PIR sensor'
    then:
        - if ${properties.get('occupancy') == 1}:
            - action: zigbee.mqtt.device_set
              args:
                  device: 'Black dimmer'
                  property: 'state'
                  value: 'ON'
            - action: alarm.add
              args:
                  when: 60
                  actions:
                      - action: zigbee.mqtt.device_set
                        args:
                            device: 'Black dimmer'
                            property: 'state'
                            value: 'OFF'
                  enabled: True
```

 there is the traceback.

```
2020-06-03 11:47:07,824| INFO|platypush.event.hook|Running hook PirTriggerLightOn triggered by an event
2020-06-03 11:47:07,828| INFO|platypush.procedure|Executing procedure PirTriggerLightOn__Hook
2020-06-03 11:47:07,834| INFO|platypush.procedure|Executing procedure PirTriggerLightOn__Hook__if_1
2020-06-03 11:47:07,946| INFO|platypush|Received event: {"type": "event", "target": "zigbee-gateway", "origin": "zigbee-gateway", "id": "4c9fb7ef7e6cf727dc179e2632714a2b", "_timestamp": 1591156027.9400332, "args": {"type": "platypush.message.event.zigbee.mqtt.ZigbeeMqttDevicePropertySetEvent", "host": "localhost", "port": 1883, "device": "Black dimmer", "properties": {"state": "ON", "linkquality": 134, "power": 6, "brightness": 200, "update_available": false}}}
2020-06-03 11:47:07,949| INFO|platypush.message.request|Processed response from action zigbee.mqtt.device_set: {"id": null, "type": "response", "target": null, "origin": null, "_timestamp": 1591156027.9487357, "response": {"output": {"state": "ON"}, "errors": []}}
2020-06-03 11:47:08,562|ERROR|AlarmPlugin|'NoneType' object has no attribute 'add_alarm'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/platypush/message/request/__init__.py", line 228, in _thread_func
    response = plugin.run(method=method_name, **args)
  File "/usr/local/lib/python3.7/dist-packages/platypush/plugins/__init__.py", line 54, in run
    return getattr(self, method)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/platypush/plugins/__init__.py", line 14, in _execute_action
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/platypush/plugins/alarm.py", line 41, in add
    alarm = self._get_backend().add_alarm(when=when, audio_file=audio_file, actions=actions or [],
AttributeError: 'NoneType' object has no attribute 'add_alarm'
2020-06-03 11:47:08,564|WARNING|platypush.message.request|Uncaught exception while processing response from action [alarm.add]: 'NoneType' object has no attribute 'add_alarm'
```

**Comment by BlackLight** [comment]
The `alarm` plugin and backend are quite tightly coupled. The plugin allows you to dynamically control alarms, but it's the backend the one that runs in the background and executes the alarm logic. It seems in your case that you haven't enabled the backend, and that explains the error. This should suffice:

```yaml
backend.alarm:
  enabled: true
```

Also, note that the alarm plugin may be a bit of an overkill for this type of task - it's mostly used for "actual" alarms, while your case is more that of a set of actions to be run after a certain amount of seconds. [`utils.set_timeout`](https://platypush.readthedocs.io/en/latest/platypush/plugins/utils.html#platypush.plugins.utils.UtilsPlugin.set_timeout) could be a better pick:

```yaml
- action: utils.set_timeout
  seconds: 60
  actions:
    - # Your actions
```

**Comment by BlackLight** [comment]
Closing for inactivity - if you still have questions feel free to reopen it.
